// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.IncomingPortal":       schema_pkg_apis_tesseract_v1alpha1_IncomingPortal(ref),
		"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.IncomingPortalSpec":   schema_pkg_apis_tesseract_v1alpha1_IncomingPortalSpec(ref),
		"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.IncomingPortalStatus": schema_pkg_apis_tesseract_v1alpha1_IncomingPortalStatus(ref),
		"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.OutgoingPortal":       schema_pkg_apis_tesseract_v1alpha1_OutgoingPortal(ref),
		"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.OutgoingPortalSpec":   schema_pkg_apis_tesseract_v1alpha1_OutgoingPortalSpec(ref),
		"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.OutgoingPortalStatus": schema_pkg_apis_tesseract_v1alpha1_OutgoingPortalStatus(ref),
	}
}

func schema_pkg_apis_tesseract_v1alpha1_IncomingPortal(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "IncomingPortal is the Schema for the incomingportals API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.IncomingPortalSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.IncomingPortalStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.IncomingPortalSpec", "github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.IncomingPortalStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tesseract_v1alpha1_IncomingPortalSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "IncomingPortalSpec defines the desired state of IncomingPortal",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tesseract_v1alpha1_IncomingPortalStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "IncomingPortalStatus defines the observed state of IncomingPortal",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tesseract_v1alpha1_OutgoingPortal(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OutgoingPortal is the Schema for the outgoingportals API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.OutgoingPortalSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.OutgoingPortalStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.OutgoingPortalSpec", "github.com/dirty49374/tesseract-operator/pkg/apis/tesseract/v1alpha1.OutgoingPortalStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tesseract_v1alpha1_OutgoingPortalSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OutgoingPortalSpec defines the desired state of OutgoingPortal",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tesseract_v1alpha1_OutgoingPortalStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OutgoingPortalStatus defines the observed state of OutgoingPortal",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
