// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncomingPortal) DeepCopyInto(out *IncomingPortal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncomingPortal.
func (in *IncomingPortal) DeepCopy() *IncomingPortal {
	if in == nil {
		return nil
	}
	out := new(IncomingPortal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncomingPortal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncomingPortalList) DeepCopyInto(out *IncomingPortalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IncomingPortal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncomingPortalList.
func (in *IncomingPortalList) DeepCopy() *IncomingPortalList {
	if in == nil {
		return nil
	}
	out := new(IncomingPortalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncomingPortalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncomingPortalSpec) DeepCopyInto(out *IncomingPortalSpec) {
	*out = *in
	if in.LocalPorts != nil {
		in, out := &in.LocalPorts, &out.LocalPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncomingPortalSpec.
func (in *IncomingPortalSpec) DeepCopy() *IncomingPortalSpec {
	if in == nil {
		return nil
	}
	out := new(IncomingPortalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncomingPortalStatus) DeepCopyInto(out *IncomingPortalStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncomingPortalStatus.
func (in *IncomingPortalStatus) DeepCopy() *IncomingPortalStatus {
	if in == nil {
		return nil
	}
	out := new(IncomingPortalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutgoingPortal) DeepCopyInto(out *OutgoingPortal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutgoingPortal.
func (in *OutgoingPortal) DeepCopy() *OutgoingPortal {
	if in == nil {
		return nil
	}
	out := new(OutgoingPortal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OutgoingPortal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutgoingPortalList) DeepCopyInto(out *OutgoingPortalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OutgoingPortal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutgoingPortalList.
func (in *OutgoingPortalList) DeepCopy() *OutgoingPortalList {
	if in == nil {
		return nil
	}
	out := new(OutgoingPortalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OutgoingPortalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutgoingPortalSpec) DeepCopyInto(out *OutgoingPortalSpec) {
	*out = *in
	if in.RemotePorts != nil {
		in, out := &in.RemotePorts, &out.RemotePorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutgoingPortalSpec.
func (in *OutgoingPortalSpec) DeepCopy() *OutgoingPortalSpec {
	if in == nil {
		return nil
	}
	out := new(OutgoingPortalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutgoingPortalStatus) DeepCopyInto(out *OutgoingPortalStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutgoingPortalStatus.
func (in *OutgoingPortalStatus) DeepCopy() *OutgoingPortalStatus {
	if in == nil {
		return nil
	}
	out := new(OutgoingPortalStatus)
	in.DeepCopyInto(out)
	return out
}
